version: '3.8'
services:
  product-service:
    build: ./product-service
    ports:
      - "5002:5002"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/products"]
      interval: 10s
      timeout: 5s
      retries: 3

  user-service:
    build: ./user-service
    ports:
      - "5001:5001"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/users"]
      interval: 10s
      timeout: 5s
      retries: 3

  order-service:
    build: ./order-service
    ports:
      - "5003:5003"
    networks:
      - app-network
    depends_on:
      - user-service
      - product-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/orders"]
      interval: 10s
      timeout: 5s
      retries: 3

  client-service:
    # build: ./frontend
    build: ./client
    ports:
      - "5000:80" # Map port 80 inside container to 5000 on host
    networks:
      - app-network
    depends_on:
      - order-service
      - user-service
      - product-service

networks:
  app-network:
    driver: bridge
